INSERT INTO vehicle_brand (id, brand_name_en) VALUES
(1, 'Airgator Airboats'),
(2, 'Albany'),
(3, 'Annis'),
(4, 'Asstone'),
(5, 'Benefactor'),
(6, 'Bürgerfahrzeug'),
(7, 'Bollokan'),
(8, 'Bravado'),
(9, 'Brute'),
(10, 'Buckingham'),
(11, 'Canis'),
(12, 'Cheval'),
(13, 'Classique'),
(14, 'Coil'),
(15, 'Crest Kayaks'),
(16, 'Declasse'),
(17, 'Dewbauchee'),
(18, 'Dinka'),
(19, 'Dundreary'),
(20, 'Eberhard'),
(21, 'Emperor'),
(22, 'Enus'),
(23, 'Fathom'),
(24, 'Gallivanter'),
(25, 'Grotti'),
(26, 'Hijak'),
(27, 'HVY'),
(28, 'Imponte'),
(29, 'Invetero'),
(30, 'Jack Sheepe'),
(31, 'JoBuilt'),
(32, 'Kraken Submersibles'),
(33, 'Lampadati'),
(34, 'Liberty City Cycles'),
(35, 'Liberty Chop Shop'),
(36, 'Karin'),
(37, 'Chariot'),
(38, 'Principe'),
(39, 'Stanley'),
(40, 'Western Company'),
(41, 'Lure Predator'),
(42, 'Maibatsu Corporation'),
(43, 'Mammoth'),
(44, 'Maxwell'),
(45, 'MTL'),
(46, 'Nagasaki'),
(47, 'Obey'),
(48, 'Ocelot'),
(49, 'Överflöd'),
(50, 'PED Cycles'),
(51, 'Pegassi'),
(52, 'Penaud'),
(53, 'Pfister'),
(54, 'Progen'),
(55, 'RUNE'),
(56, 'Schyster'),
(57, 'Shitzu'),
(58, 'Skiver'),
(59, 'Speedophile'),
(60, 'Steel Horse'),
(61, 'Toundra'),
(62, 'Tri-Cycles'),
(63, 'Truffade'),
(64, 'Übermacht'),
(65, 'Vapid'),
(66, 'Vulcar'),
(67, 'Vysser'),
(68, 'Weeny'),
(69, 'Western Motorcycle Company'),
(70, 'Willard'),
(71, 'Zirconium');